#ifndef PROTOCOL_H
#define PROTOCOL_H

typedef unsigned int uint;

enum ENUM_TYPE//消息类型的枚举值
{
    ENUM_TYPE_MIN = 0,
    ENUM_TYPE_REGIST_REQ,
    ENUM_TYPE_REGIST_RES,
    ENUM_TYPE_LOGIN_REQ,
    ENUM_TYPE_LOGIN_RES,
    ENUM_TYPE_FIND_USER_REQ,
    ENUM_TYPE_FIND_USER_RES,
    ENUM_TYPE_ONLINE_USER_REQ,
    ENUM_TYPE_ONLINE_USER_RES,
    ENUM_TYPE_ADJUDGE_ADD_FRIEND_REQ,
    ENUM_TYPE_ADJUDGE_ADD_FRIEND_RES,
    ENUM_TYPE_AGREE_ADD_FRIEND_REQ,
    ENUM_TYPE_AGREE_ADD_FRIEND_RES,
    ENUM_TYPE_FLUSH_FRIEND_REQ,
    ENUM_TYPE_FLUSH_FRIEND_RES,
    ENUM_TYPE_DELETE_FRIEND_REQ,
    ENUM_TYPE_DELETE_FRIEND_RES,
    ENUM_TYPE_CHAT_REQ,
    ENUM_TYPE_CHAT_RES,
    ENUM_TYPE_MKDIR_REQ,
    ENUM_TYPE_MKDIR_RES,
    ENUM_TYPE_FLUSH_FILE_REQ,
    ENUM_TYPE_FLUSH_FILE_RES,
    ENUM_TYPE_DEL_FILE_REQ,
    ENUM_TYPE_DEL_FILE_RES,
    ENUM_TYPE_RENAME_FILE_REQ,
    ENUM_TYPE_RENAME_FILE_RES,
    ENUM_TYPE_INIT_UPLOAD_FILE_REQ,
    ENUM_TYPE_INIT_UPLOAD_FILE_RES,
    ENUM_TYPE_DATA_UPLOAD_FILE_REQ,
    ENUM_TYPE_DATA_UPLOAD_FILE_RES,
    ENUM_TYPE_INIT_SHARE_FILE_REQ,
    ENUM_TYPE_INIT_SHARE_FILE_RES,
    ENUM_TYPE_AGREE_SHARE_FILE_REQ,
    ENUM_TYPE_AGREE_SHARE_FILE_RES,
};

struct PDU//协议数据单元
{
    uint uiTotalLen;    //协议的总长度
    uint uiMsgLen;      //柔性数组的长度
    uint uiType;        //消息类型
    char caData[64];    //参数，如果数据能放下就放这里
    char caMsg[];       //消息，柔性数组，如果数据放不下参数中，就放这里
};

PDU* initPDU(uint uiMsgLen);

struct FileInfo
{
    char caName[32];
    uint uiType;
};

#endif // PROTOCOL_H
